import React, {useEffect,useId,useState} from 'react';
import {Field, Obj, buildPatch, fmt, number,passwordEdit,scaledInput,changeSummary,Change} from './model';
const dirtyForms=new Set<string>();
export const hasUnsavedChanges=()=>dirtyForms.size>0;
export function useUnsavedChanges(dirty:boolean){const id=useId();useEffect(()=>{if(dirty)dirtyForms.add(id);else dirtyForms.delete(id);return()=>{dirtyForms.delete(id);};},[id,dirty]);}

export function Icon({name='grid'}:{name?:string}) {const paths:Record<string,string>={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',plug:'M8 3v5m8-5v5M6 8h12v3a6 6 0 0 1-12 0V8m6 9v4',device:'M5 3h14v18H5z M9 7h6m-6 4h6m-4 6h2',settings:'M4 7h16M4 17h16M8 4v6m8 4v6',pulse:'M2 12h5l3-8 4 16 3-8h5',arrow:'M5 12h14m-6-6 6 6-6 6',check:'M5 12l4 4L19 6',copy:'M9 8h11v13H9z M5 16H3V3h11v2',refresh:'M20 7V3l-3 3a8 8 0 1 0 3 9M20 7h-5'};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.grid}/></svg>;}
export function Card({title,description,action,children,className=''}:{title?:string;description?:string;action?:React.ReactNode;children:React.ReactNode;className?:string}) {return <section className={'card '+className}>{title&&<div className="card-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>}{children}</section>;}
export function Stat({label,value,sub,accent=false}:{label:string;value:string;sub:string;accent?:boolean}) {return <div className={'stat card '+(accent?'accent':'')}><p>{label}</p><strong>{value}</strong><small>{sub}</small></div>;}
export function FieldInput({field:f,value,onChange,error,disabled=false}:{field:Field;value:unknown;onChange:(v:unknown)=>void;error?:string;disabled?:boolean}) {
 const id='field-'+f.key.replaceAll('.','-'), scale=f.scale||1;
 return <div className={'field '+(error?'invalid':'')}><label htmlFor={id}>{f.label}{f.unit&&<span className="unit">{f.unit}</span>}</label>{f.options?<select id={id} disabled={disabled} value={String(value??'')} onChange={e=>onChange(Number(e.target.value))}>{f.options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:f.type==='boolean'?<label className="switch-line"><input id={id} type="checkbox" checked={value===true} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span>{value===true?'已开启':'已关闭'}</span></label>:<input id={id} type={f.type==='number'?'number':f.type==='password'?'password':'text'} autoComplete={f.type==='password'?'new-password':'off'} min={f.min===undefined?undefined:f.min/scale} max={f.max===undefined?undefined:f.max/scale} step={scale>1?1/scale:1} value={f.type==='number'?(number(value)===null?'':Number(value)/scale):typeof value==='string'?value:''} disabled={disabled} aria-invalid={!!error} aria-describedby={id+'-hint'} onChange={e=>onChange(f.type==='number'?scaledInput(e.target.value,scale):e.target.value)}/>}<small id={id+'-hint'} className={error?'field-error':'hint'}>{error||f.hint}</small></div>;
}
export function ConfigForm({fields,baseline,onSave,disabled=false,device=false,children,label='保存设置',hidden=[],preset}:{fields:Field[];baseline:Obj;onSave:(patch:Obj)=>Promise<boolean>;disabled?:boolean;device?:boolean;children?:React.ReactNode;label?:string;hidden?:string[];preset?:Obj}) {
 const [draft,setDraft]=useState<Obj>({}),[errors,setErrors]=useState<Obj>({}),[passwordMode,setPasswordMode]=useState('keep');
 useUnsavedChanges(Object.keys(draft).some(k=>draft[k]!==baseline[k])||passwordMode!=='keep');
 const presetKey=JSON.stringify(preset);useEffect(()=>{if(preset)setDraft(d=>({...d,...preset}));},[presetKey]);
 const values={...baseline,...draft};
 const editable=fields.filter(f=>!hidden.includes(f.key) && !(f.key.startsWith('ip.') && f.key!=='ip.dhcp' && values['ip.dhcp']!==false) && !(f.key==='wifi.password'&&passwordMode==='keep'));
 const changes=changeSummary(editable,draft,baseline,passwordMode);
 const save=async(e:React.FormEvent)=>{e.preventDefault();let d={...draft};if(fields.some(f=>f.key==='wifi.password')) {if(passwordMode==='keep')delete d['wifi.password'];else d['wifi.password']=passwordMode==='open'?'':(draft['wifi.password']??'');}const {patch,errors:next}=buildPatch(editable,d,baseline);const passwordError=passwordEdit(passwordMode,d['wifi.password']).error;if(passwordError)next['wifi.password']=passwordError;if(fields.some(f=>f.key==='wifi.ssid') && (!values['wifi.ssid']||String(values['wifi.ssid']).length===0))next['wifi.ssid']='请填写网络名称';if(patch.api_listen && patch.api_listen===values.admin_listen || patch.admin_listen && patch.admin_listen===values.api_listen)next.admin_listen='管理页面和 API 必须使用不同地址';setErrors(next);if(Object.keys(next).length)return;if(!Object.keys(patch).length){setErrors({_form:'尚未修改任何设置。'});return;}if(await onSave(patch)){setDraft({});setPasswordMode('keep');setErrors({});}};
 return <form onSubmit={e=>void save(e)} noValidate><fieldset disabled={disabled}><div className="form-grid">{fields.filter(f=>!hidden.includes(f.key)&&!(f.key.startsWith('ip.')&&f.key!=='ip.dhcp'&&values['ip.dhcp']!==false)).map(f=>f.key==='wifi.password'?<div className="field" key={f.key}><label htmlFor="wifi-password-mode">Wi-Fi 密码</label><select id="wifi-password-mode" value={passwordMode} onChange={e=>{setPasswordMode(e.target.value);setDraft(d=>{const x={...d};delete x['wifi.password'];return x;});}}><option value="keep">{baseline['wifi.password']?'保持已保存的密码':'保持当前密码设置'}</option><option value="replace">更换密码</option><option value="open">这是无需密码的开放网络</option></select>{passwordMode==='replace'&&<input aria-label="新的 Wi-Fi 密码" type="password" autoComplete="new-password" value={draft['wifi.password']||''} onChange={e=>setDraft(d=>({...d,'wifi.password':e.target.value}))}/>}<small className={errors[f.key]?'field-error':'hint'}>{errors[f.key]||'已保存密码不回读。修改网络时，请确认密码是否也需要更换。'}</small></div>:<FieldInput key={f.key} field={f} value={values[f.key]} error={errors[f.key]} onChange={v=>{setDraft(d=>({...d,[f.key]:v}));setErrors(es=>({...es,[f.key]:''}));}}/>)}</div>{children}<ChangeSummary changes={changes}/><div className="form-footer"><span>{errors._form?<span className="field-error">{errors._form}</span>:device?'应用后验证连接，再确认保存。':'仅保存修改的字段。'}</span><button className="primary" type="submit">{label}</button></div></fieldset></form>;
}
type Series={label:string;color:string;values:(number|null)[]};
export function Chart({series,unit,empty='正在收集数据，稍后显示趋势。'}:{series:Series[];unit:string;empty?:string}) {
 const all=series.flatMap(s=>s.values).filter((v):v is number=>v!==null&&Number.isFinite(v)),max=Math.max(1,...all),count=Math.max(2,...series.map(s=>s.values.length));
 const paths=(values:(number|null)[])=>{let out='',start=true;values.forEach((v,i)=>{if(v===null||!Number.isFinite(v)){start=true;return;}out+=`${start?'M':'L'}${42+i/(count-1)*506},${145-v/max*115} `;start=false;});return out;};
 return <div className="chart"><div className="chart-legend">{series.map(s=><span key={s.label}><i style={{background:s.color}}/>{s.label}<b>{fmt(s.values.at(-1),1)} {unit}</b></span>)}</div>{!all.length?<div className="chart-empty"><Icon name="pulse"/><p>{empty}</p></div>:<svg viewBox="0 0 570 190" role="img" aria-label={series.map(s=>`${s.label}，最新 ${fmt(s.values.at(-1),1)} ${unit}`).join('；')}><title>页面打开后的有效采样；断线处不连接曲线</title>{[0,.5,1].map(n=><g key={n}><line x1="42" x2="550" y1={145-n*115} y2={145-n*115} stroke="#e9edf3"/><text x="34" y={149-n*115} textAnchor="end" fill="#8b96a8" fontSize="10">{fmt(max*n,1)}</text></g>)}{series.map(s=><path key={s.label} d={paths(s.values)} stroke={s.color} strokeWidth="2.5" fill="none" strokeLinecap="round"/>)}<text x="42" y="178" fill="#8b96a8" fontSize="11">观察开始</text><text x="550" y="178" textAnchor="end" fill="#8b96a8" fontSize="11">现在</text></svg>}</div>;
}
export function Details({value}:{value:unknown}) {return <pre className="raw">{JSON.stringify(value,null,2)||'暂无数据'}</pre>;}


export function ChangeSummary({changes}:{changes:Change[]}){return changes.length?<div className="change-summary" aria-label="保存前变更摘要"><strong>即将修改 {changes.length} 项</strong><dl>{changes.map(c=><div key={c.key}><dt>{c.label}</dt><dd><span>{c.before}</span><span className="change-arrow" aria-label="改为">→</span><b>{c.after}</b></dd></div>)}</dl><small>下列变更将在保存时校验；尚未写入配置。</small></div>:null;}
