import React,{useCallback,useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {request,withDeadline} from './api';
import {EventRecovery} from './recovery';
import {Obj,Point,bytes,countdown,explainError,fmt,fresh,object,sampleHistory,transport,signalQuality} from './model';
import {Card,Chart,Icon,Stat,hasUnsavedChanges} from './components';
import {AppsPage,DevicePage,SettingsPage,MaintenancePage,UIContext} from './pages';
import './style.css';
const pages=[['overview','总览','grid'],['apps','接入应用','plug'],['device','设备与网络','device'],['settings','服务设置','settings'],['maintenance','诊断与维护','pulse']];
const subtitles:Obj={overview:'连接、用量与设备健康，一目了然。',apps:'将本机代理连接到你习惯使用的 AI 应用。',device:'管理设备连接和无线网络。',settings:'配置模型服务与请求行为。',maintenance:'检查问题、导出诊断与维护设备。'};
function App(){
 const [page,setPage]=useState(()=>pages.some(p=>p[0]===location.hash.slice(1))?location.hash.slice(1):'overview'),[state,setState]=useState<Obj>({}),[config,setConfig]=useState<Obj>({}),[capabilities,setCapabilities]=useState<Obj>({});
 const navigate=(next:string)=>{location.hash=next;};
 useEffect(()=>{const change=()=>{const next=pages.some(p=>p[0]===location.hash.slice(1))?location.hash.slice(1):'overview';if(next!==page&&hasUnsavedChanges()&&!window.confirm('此页面有尚未保存的修改，离开后这些输入会丢失。继续吗？')){window.history.replaceState(null,'','#'+page);return;}setPage(next);};const unload=(e:BeforeUnloadEvent)=>{if(hasUnsavedChanges()){e.preventDefault();e.returnValue='';}};window.addEventListener('hashchange',change);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('hashchange',change);window.removeEventListener('beforeunload',unload);};},[page]);
 const [connected,setConnected]=useState(false),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0),[feed,setFeed]=useState('正在连接'),[feedExhausted,setFeedExhausted]=useState(false),[now,setNow]=useState(Date.now());
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),busyRef=useRef(false),[history,setHistory]=useState<Point[]>([]),[checkingTransaction,setCheckingTransaction]=useState(false);
 const lastState=useRef<Obj>({}),sampleInterval=useRef(1000);sampleInterval.current=Number(config.device?.effective?.['telemetry.interval_ms']||1000);
 const accept=useCallback((v:unknown)=>{const s=object(v);if(!('connected'in s))throw new Error('管理服务未返回有效设备状态。');const p=lastState.current;s._deviceObservedAt=s.device&&p.device&&s.device.session===p.device.session&&s.device.sample_time_ms===p.device.sample_time_ms?p._deviceObservedAt:Date.now();lastState.current=s;setState(s);setHistory(h=>sampleHistory(h,s,Date.now(),sampleInterval.current));},[]);
 const refresh=useCallback(async()=>{accept(await request('/state'));},[accept]);
 const acceptConfig=useCallback((v:unknown)=>{const c=object(v);setConfig({...c,_receivedAt:Date.now()});return c;},[]);
 const readConfig=useCallback(async()=>acceptConfig(await request('/config')),[acceptConfig]);
 const reload=useCallback(async()=>{await refresh();await readConfig();setCapabilities(object(await request('/capabilities')));},[refresh,readConfig]);
 const run=useCallback(async(action:()=>Promise<unknown>,success='操作已完成')=>{if(busyRef.current)return false;busyRef.current=true;setBusy(true);setError('');setMessage('');try{await action();setMessage(success);return true;}catch(e){setError(explainError(e));return false;}finally{busyRef.current=false;setBusy(false);}},[]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{let alive=true,stream:EventSource|undefined;const controller=new AbortController();setLoading(true);setError('');setFeedExhausted(false);
  const recovery=new EventRecovery(()=>{if(alive){setFeedExhausted(true);setFeed('自动恢复已尝试 5 次，实时状态已暂停');}});
  const receive=(e:MessageEvent)=>{if(!alive)return;try{accept(JSON.parse(e.data));}catch{setFeed('状态格式异常，等待下一次更新');}};
  const closeStream=()=>{if(!stream)return;stream.onerror=null;stream.onopen=null;stream.onmessage=null;stream.removeEventListener('state',receive as EventListener);stream.removeEventListener('snapshot',receive as EventListener);stream.close();stream=undefined;};
  const recover=()=>{if(!alive)return;closeStream();const retryNumber=recovery.schedule(()=>{void withDeadline(signal=>request('/state','GET',undefined,signal),controller.signal).then(v=>{if(!alive)return;accept(v);subscribe();}).catch(recover);});if(retryNumber!==null)setFeed(`状态连接中断，正在自动恢复（${retryNumber}/5）`);};
  const subscribe=()=>{if(!alive)return;closeStream();stream=new EventSource('/admin/v1/events');stream.addEventListener('state',receive as EventListener);stream.addEventListener('snapshot',receive as EventListener);stream.onmessage=receive;stream.onopen=()=>{if(alive){setFeed('实时更新已连接');recovery.opened();}};stream.onerror=recover;};
  void withDeadline(signal=>request('/state','GET',undefined,signal),controller.signal).then(async v=>{if(!alive)return;accept(v);setConnected(true);subscribe();const results=await Promise.allSettled([request('/config'),request('/capabilities')]);if(!alive)return;const c=results[0];if(c.status==='fulfilled')acceptConfig(c.value);else setError('配置暂未读取成功，请点击顶部刷新重试。');const cp=results[1];if(cp.status==='fulfilled')setCapabilities(object(cp.value));}).catch(e=>{if(alive){setConnected(false);setError(explainError(e));}}).finally(()=>{if(alive)setLoading(false);});
  return()=>{alive=false;controller.abort();closeStream();recovery.dispose();};
 },[attempt,accept]);
 const pending=Boolean(config.device?.pending);
 useEffect(()=>{if(!state.paired||!state.device)return;let alive=true;void Promise.all([request('/config'),request('/capabilities')]).then(([c,cp])=>{if(alive){acceptConfig(c);setCapabilities(object(cp));}}).catch(()=>{});return()=>{alive=false;};},[state.device?.session,state.device?.revision,state.paired]);
 useEffect(()=>{if(!pending&&!checkingTransaction)return;let alive=true,running=false;const timer=setInterval(()=>{if(running)return;running=true;void request('/config').then(v=>{if(alive){const c=acceptConfig(v);if(!c.device?.pending&&c.device)setCheckingTransaction(false);}}).catch(()=>{/* unresolved operation remains visible */}).finally(()=>{running=false;});},2000);return()=>{alive=false;clearInterval(timer);};},[pending,checkingTransaction]);
 const d=object(state.device),net=object(d.network),llm=object(state.llm),host=object(state.host),deviceConfig=object(config.device?.effective),active=Number(llm.active||0);
 const kind=transport(state),isFresh=!feedExhausted&&fresh(state,now,Number(deviceConfig['telemetry.interval_ms']||1000)),left=countdown(config,state,now),maintenance=Boolean(host.firmware_upload),blocked=busy||maintenance;
 useEffect(()=>{if(!isFresh)setHistory(h=>sampleHistory(h,feedExhausted?{...state,_feedUnavailable:true}:state,Date.now(),sampleInterval.current));},[isFresh,feedExhausted]);
 const serviceConfigured=Boolean(config.host?.upstream_url&&config.secrets?.upstream_key_set);
 const status=llm.paused?'已暂停接收新请求':maintenance?'正在维护设备':!state.connected?'设备未连接':!state.paired?'设备等待配对':!isFresh?'正在确认设备状态':!net.connected?'Wi-Fi 尚未连接':!serviceConfigured?'上游服务待配置':'代理已就绪';
 const statusGood=isFresh&&net.connected&&serviceConfigured&&!llm.paused&&!maintenance;
 const actual=config.effective_listeners?.api_listen,baseURL=actual?`http://${actual}/v1`:'';
 const saveHost=async(patch:Obj)=>run(async()=>{await request('/config','PATCH',{host:patch});await readConfig();},'设置已保存。监听地址需重启后台，其他服务设置用于后续请求。');
 const saveDevice=async(patch:Obj)=>{if(active>0){setError(`仍有 ${active} 个请求运行，请先暂停新请求并等待完成。`);return false;}return run(async()=>{setCheckingTransaction(true);try{await request('/config','PATCH',{device:patch});}finally{await readConfig();await refresh();}},'设置已临时应用，请在倒计时内确认保存，或恢复原配置。');};
 const action=(path:string,body?:unknown,success?:string)=>void run(async()=>{await request(path,'POST',body);await reload();},success);
 const ui:UIContext={state,config,capabilities,deviceConfig,isFresh,kind,blocked,pending,active,baseURL,statusGood,run,reload,readConfig,saveHost,saveDevice,action,setError,onStop:()=>setConnected(false)};
 return <div className="app-shell"><aside className="sidebar"><a href="#" className="brand" onClick={e=>{e.preventDefault();navigate('overview');}}><span className="brand-mark"><Icon name="pulse"/></span><span>uart<span className="brand-number">2</span>llm<small>个人 AI 连接中心</small></span></a><span className="nav-caption">工作空间</span><nav aria-label="管理导航">{pages.map(([id,label,icon])=><button key={id} aria-current={page===id?'page':undefined} className={page===id?'selected':''} disabled={!connected} onClick={()=>navigate(id)}><Icon name={icon}/>{label}{page===id&&<i/>}</button>)}</nav><div className="sidebar-bottom"><span className={'status-dot '+(statusGood?'good':'')}/><div>{statusGood?'设备在线':'等待就绪'}<small>{kind==='未知'?'等待识别连接':kind==='USB'?'原生 USB · ESP32-S3':'UART · ESP32-S3'}</small></div></div></aside>
 <main><header className="page-header"><div><div className="eyebrow">UART2LLM / 本机控制台</div><h1>{pages.find(p=>p[0]===page)?.[1]}</h1><p>{subtitles[page]}</p></div><div className="header-actions"><span className="pill"><span className="status-dot good"/>免登录 · 本机访问</span><button className="icon-button" aria-label="刷新状态和配置" disabled={busy||!connected} onClick={()=>void run(reload,'状态和配置已刷新。')}><Icon name="refresh"/></button></div></header>
 {error&&<div className="notice error" role="alert"><span>{error}</span><button aria-label="关闭错误提示" onClick={()=>setError('')}>×</button></div>}{message&&<div className="notice success" role="status"><span>{message}</span><button aria-label="关闭完成提示" onClick={()=>setMessage('')}>×</button></div>}
 {feedExhausted&&connected&&<div className="notice warning" role="status"><span>实时状态自动恢复已尝试 5 次。保留最后一次快照，过期数据不代表当前状态。</span><button disabled={loading} onClick={()=>setAttempt(a=>a+1)}>重新连接实时状态</button></div>}
 {!connected?<Card title={loading?'正在连接本机管理服务':'本机管理服务暂不可用'} description="无需填写密码或管理令牌。后台启动后，页面会自动建立本机会话。"><div className="empty-state"><Icon name="plug"/><p>{loading?'正在检查服务状态…':'请确认 uart2llm 后台已运行，然后重新连接。'}</p><button className="primary" disabled={loading} onClick={()=>setAttempt(a=>a+1)}>重新连接</button></div></Card>:<>
 {(pending||checkingTransaction)&&<section className="transaction" role="status"><div><strong>{pending?'有设置等待确认保存':'正在核对上次设置操作的结果'}</strong><p>{pending?`设置已临时应用。${left===null?'正在重新获取设备确认时间。':`剩余约 ${left} 秒，超时将恢复原配置。`}`:'结果可能尚未确定。正在读取设备状态，不会重复提交。'}</p></div><div className="actions"><button disabled={blocked||!isFresh} onClick={()=>void run(async()=>{await request('/config/rollback','POST');setCheckingTransaction(true);await readConfig();},'已请求恢复原配置，等待设备完成。')}>恢复原配置</button><button className="primary" disabled={blocked||!pending||!isFresh||left===0||left===null||Boolean(deviceConfig['wifi.ssid']&&!net.connected)} onClick={()=>void run(async()=>{await request('/config/confirm','POST');await readConfig();setCheckingTransaction(false);},'配置已确认保存，设备重启后保留。')}>确认保存</button></div></section>}
 <div className={'connection-banner '+(statusGood?'ready':'attention')}><div className="banner-icon"><Icon name={statusGood?'check':'plug'}/></div><div><strong>{status}</strong><p>{statusGood?`本机 → ${kind==='USB'?'原生 USB':kind} → ${net.ssid||'Wi-Fi'} · 上游${config.secrets?.upstream_key_set?'已配置':'尚未设置密钥'}`:llm.paused?'已有回答继续完成；恢复后接受新请求。':!state.connected?'请在“设备与网络”中选择并连接开发板。':!state.paired?'请完成设备配对，随后配置无线网络。':!isFresh?'当前显示上一次数据，正在等待有效的新快照。':net.connected&&!serviceConfigured?'请在服务设置中保存上游地址和 API Key。':'请检查 Wi-Fi 网络名称、密码和设备信号。'}</p></div><button disabled={blocked} onClick={()=>action('/proxy/pause',{paused:!llm.paused},llm.paused?'已恢复接收新请求。':'已暂停新请求，已有回答继续完成。')}>{llm.paused?'恢复代理':'暂停代理'}</button></div>
 {page==='overview'&&<><div className="stat-grid"><Stat label="本次运行请求" value={fmt(llm.requests)} sub={`已完成 ${fmt(llm.completed)} · 最近一分钟 ${fmt(llm.requests_last_60s)}`} accent/><Stat label="当前并发" value={`${fmt(llm.active)} / ${config.host?.max_concurrent||4}`} sub="达到容量时，新请求会立即提示忙碌"/><Stat label="累计 Token" value={fmt(llm.total_tokens)} sub={`已获取用量 ${fmt(llm.usage_reported)} 次 · 未上报 ${fmt(llm.usage_missing)} 次`}/><Stat label="请求成功率" value={llm.completed?`${fmt(llm.succeeded/llm.completed*100,1)}%`:'—'} sub={`成功 ${fmt(llm.succeeded)} · 失败 ${fmt(llm.failed)}`}/></div>
 <div className="dashboard-grid"><Card title="连接吞吐" description="最近 5 分钟 · 页面打开后的采样 · 含协议开销" action={<span className="pill">KiB/s</span>}><Chart unit="KiB/s" series={[{label:'设备 → 电脑',color:'#4169e1',values:history.map(p=>p.down)},{label:'电脑 → 设备',color:'#16a394',values:history.map(p=>p.up)}]}/></Card><Card title="请求活动" description="最近一分钟请求数的变化，不是每秒请求数"><Chart unit="次/分钟" series={[{label:'最近一分钟',color:'#8b5cf6',values:history.map(p=>p.requests)}]}/></Card>
 <Card title="用量与响应" description="本次后台运行累计 · 请求完成后结算"><div className="token-total"><strong>{fmt(llm.total_tokens)}</strong><span>Token</span></div><div className="token-bar" role="img" aria-label={`输入 ${fmt(llm.prompt_tokens)}，输出 ${fmt(llm.completion_tokens)} Token`}><i style={{width:`${llm.total_tokens?Math.min(100,llm.prompt_tokens/llm.total_tokens*100):0}%`}}/><b style={{width:`${llm.total_tokens?Math.min(100,llm.completion_tokens/llm.total_tokens*100):0}%`}}/></div><dl className="detail-list"><div><dt>输入 / 输出</dt><dd>{fmt(llm.prompt_tokens)} / {fmt(llm.completion_tokens)}</dd></div><div><dt>其中缓存命中</dt><dd>{fmt(llm.cached_tokens)} Token</dd></div><div><dt>平均响应首字节</dt><dd>{llm.completed?`${fmt(llm.average_first_byte_ms/1000,2)} 秒`:'—'}</dd></div><div><dt>平均请求完成时长</dt><dd>{llm.completed?`${fmt(llm.average_duration_ms/1000,2)} 秒`:'—'}</dd></div><div><dt>最近使用模型</dt><dd>{llm.last_model||'暂无'}</dd></div></dl><p className="hint">缓存属于输入用量。首字节不是首 Token；未上报用量不估算，费用暂不计算。</p></Card>
 <Card title="设备健康" description={isFresh?'设备快照有效':'数据暂不可用或已过期'}><div className="health-grid"><div><span>无线信号</span><strong>{isFresh&&net.connected?`${signalQuality(net.rssi_dbm)} · ${fmt(net.rssi_dbm)} dBm`:'—'}</strong><small title="参考：≥ −67 dBm 良好，−75 至 −68 一般，低于 −75 较弱；实际质量还受干扰影响。">{isFresh?(net.ssid||'未连接'):'等待设备'} · 信号参考ⓘ</small></div><div><span>内部内存剩余</span><strong>{isFresh?bytes(d.memory?.internal_free):'—'}</strong><small>最低 {isFresh?bytes(d.memory?.internal_min_free):'—'}</small></div><div><span>PSRAM 剩余</span><strong>{isFresh?bytes(d.memory?.psram_free):'—'}</strong><small>任务数 {isFresh?fmt(d.memory?.tasks):'—'}</small></div><div><span>设备重传</span><strong>{isFresh?fmt(d.link?.retries):'—'}</strong><small>CRC 错误 {isFresh?fmt(d.link?.crc_errors):'—'}</small></div></div><Chart unit="KiB" series={[{label:'内部可用内存',color:'#16a394',values:history.map(p=>p.memory===null?null:p.memory/1024)}]}/></Card></div>
 <Card title="最近状态变化" description="后台保留的最新事件，不包含请求正文" action={<button onClick={()=>navigate('maintenance')}>查看诊断 <Icon name="arrow"/></button>}><Events events={Array.isArray(state.recent_changes)?state.recent_changes.slice(-6).reverse():[]}/></Card></>}
 {page==='apps'&&<AppsPage ui={ui}/>} {page==='device'&&<DevicePage ui={ui}/>} {page==='settings'&&<SettingsPage ui={ui}/>} {page==='maintenance'&&<MaintenancePage ui={ui}/>}
 <footer><span><span className={'status-dot '+(isFresh?'good':'')}/>{feed} · 最近快照 {state.sampled_at?new Date(state.sampled_at).toLocaleTimeString('zh-CN'):'—'}</span><span>关闭页面，代理继续运行</span></footer></>}
 </main></div>;
}
function Events({events}:{events:Obj[]}) {const names:Obj={connected:'设备连接',paired:'安全配对',wifi_connected:'Wi-Fi 连接',host_config_revision:'服务设置版本',device_config_revision:'设备配置版本'};return events.length?<div className="event-list">{events.map((e,i)=><div key={e.id||i}><span className="event-dot"/><strong>{names[e.field]||e.field}</strong><span>{typeof e.value==='boolean'?(e.value?'已就绪':'未就绪'):String(e.value)}</span><time>{new Date(e.time).toLocaleTimeString('zh-CN')}</time></div>)}</div>:<p className="empty-copy">暂无状态变化记录。</p>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);


