import React from 'react';
import {describe,it,expect,vi} from 'vitest';
import {renderToStaticMarkup} from 'react-dom/server';
import {buildPatch,changeSummary,countdown,deviceFields,fresh,hostFields,imageState,passwordEdit,resetReason,sampleHistory,scaledInput,signalQuality,transport,validateField,Obj} from './model';
import {Chart,ConfigForm,ChangeSummary} from './components';
import {DevicePage,UIContext} from './pages';
const baseTime=Date.parse('2026-09-16T10:00:00Z');
const snapshot=(delta=0,extra:Obj={})=>({connected:true,paired:true,sampled_at:new Date(baseTime+delta).toISOString(),link:{link:{session:42}},llm:{requests_last_60s:3},device:{session:42,sample_time_ms:10000+delta,transport:'usb_serial_jtag',uart:{active:false},link:{tx_bytes:1000+delta*2,rx_bytes:1000+delta},memory:{internal_free:100000}},...extra});
describe('complete product configuration registry',()=>{
 it('includes exactly ten host and fourteen device settings without duplicate keys',()=>{expect(hostFields).toHaveLength(10);expect(deviceFields).toHaveLength(14);expect(new Set([...hostFields,...deviceFields].map(f=>f.key)).size).toBe(24);});
 it('submits only explicit changes and never materializes a redacted password',()=>{const baseline={'wifi.ssid':'lab','wifi.password':true};const r=buildPatch(deviceFields,{'wifi.ssid':'next'},baseline);expect(r).toEqual({patch:{'wifi.ssid':'next'},errors:{}});});
 it('rejects a redacted secret accidentally supplied as an edit',()=>{expect(buildPatch(deviceFields,{'wifi.password':true},{})?.errors['wifi.password']).toBeTruthy();});
 it('does not turn empty numeric input into zero and rejects fractional concurrency',()=>{const f=hostFields.find(f=>f.key==='max_concurrent')!;expect(validateField(f,null)).toBeTruthy();expect(validateField(f,1.5)).toBeTruthy();expect(validateField(f,4)).toBe('');expect(validateField(f,5)).toBeTruthy();});
 it('converts displayed seconds exactly without rounding a fractional millisecond edit',()=>{expect(scaledInput('',1000)).toBeNull();expect(scaledInput('1.001',1000)).toBe(1001);expect(scaledInput('1.0001',1000)).not.toBe(1000);expect(validateField(deviceFields.find(f=>f.key==='tcp.connect_timeout_ms')!,scaledInput('1.0001',1000))).toBeTruthy();});
 it('checks SSID by UTF-8 bytes rather than character count',()=>{const f=deviceFields[0];expect(validateField(f,'网'.repeat(10))).toBe('');expect(validateField(f,'网'.repeat(11))).toBeTruthy();});
 it.each(['https://host/?key=private','http://host','https://u:p@host','https://host/#key','https://host/v1/../secret'])('rejects unsafe upstream URL %s',v=>expect(validateField(hostFields[0],v)).toBeTruthy());
 it('preserves literal password spaces and supports explicit open network values',()=>{const f=deviceFields.find(f=>f.key==='wifi.password')!;expect(validateField(f,' 1234567 ')).toBe('');expect(validateField(f,'')).toBe('');expect(validateField(f,'tiny')).toBeTruthy();expect(validateField(f,'z'.repeat(64))).toBeTruthy();expect(validateField(f,'a'.repeat(64))).toBe('');});
 it('never clears the password from an empty replace input',()=>{expect(passwordEdit('replace','').error).toBeTruthy();expect(passwordEdit('replace',undefined).error).toBeTruthy();expect(passwordEdit('keep',true)).toEqual({});expect(passwordEdit('open','old draft')).toEqual({value:''});expect(passwordEdit('replace',' valid password ')).toEqual({value:' valid password '});});
 it.each(['localhost:0','0.0.0.0:8765','192.168.1.1:8765','127.999.0.1:8765','localhost:65536'])('rejects invalid listener %s',v=>expect(validateField(hostFields.find(f=>f.key==='api_listen')!,v)).toBeTruthy());
 it('supports both loopback families',()=>{for(const v of ['localhost:8765','127.0.0.1:8765','[::1]:8765'])expect(validateField(hostFields.find(f=>f.key==='api_listen')!,v)).toBe('');});
 it('validates each IPv4 octet',()=>{const f=deviceFields.find(f=>f.key==='ip.address')!;expect(validateField(f,'192.168.1.50')).toBe('');expect(validateField(f,'256.1.1.1')).toBeTruthy();});
});
describe('truthful transport and history',()=>{
 it('does not infer UART from a Windows COM name or stored baud',()=>{expect(transport({link:{port:'COM4',baud:2000000}})).toBe('未知');expect(transport(snapshot())).toBe('USB');expect(transport({device:{uart:{active:true}}})).toBe('UART');});
 it('requires matching session and fresh snapshots',()=>{expect(fresh(snapshot(),baseTime)).toBe(true);expect(fresh(snapshot(),baseTime+6000)).toBe(false);expect(fresh(snapshot(0,{link:{link:{session:99}}}),baseTime)).toBe(false);expect(fresh(snapshot(0,{paired:false}),baseTime)).toBe(false);});
 it('does not let new host timestamps disguise an old device cache',()=>{expect(fresh(snapshot(20000,{_deviceObservedAt:baseTime}),baseTime+20000)).toBe(false);expect(fresh(snapshot(20000,{_deviceObservedAt:baseTime}),baseTime+20000,60000)).toBe(true);});
 it('calculates binary KiB/s in the correct directions from device counter differences',()=>{const first=sampleHistory([],snapshot(),baseTime);const second=sampleHistory(first,snapshot(1000),baseTime+1000);expect(second.at(-1)?.down).toBe(2000/1024);expect(second.at(-1)?.up).toBe(1000/1024);});
 it('does not infer throughput from request-completion byte counters',()=>{const a=snapshot();a.device.link={tx_bytes:0,rx_bytes:0};const b=snapshot(1000);b.device.link={tx_bytes:0,rx_bytes:0};b.llm={requests_last_60s:3,response_bytes:999999} as any;expect(sampleHistory(sampleHistory([],a,baseTime),b,baseTime+1000).at(-1)?.down).toBe(0);});
 it('cuts curves on session restart and counter reset',()=>{let h=sampleHistory([],snapshot(),baseTime);const next=snapshot(1000);next.device.session=99;next.link.link.session=99;h=sampleHistory(h,next,baseTime+1000);expect(h.at(-1)?.down).toBeNull();const reset=snapshot(2000);reset.device.link.tx_bytes=0;h=sampleHistory(h,reset,baseTime+2000);expect(h.at(-1)?.down).toBeNull();});
 it('does not divide by zero for repeated device cache samples',()=>{const a=snapshot(),b=snapshot(1000);b.device.sample_time_ms=a.device.sample_time_ms;expect(sampleHistory(sampleHistory([],a,baseTime),b,baseTime+1000).at(-1)?.down).toBeNull();});
 it('inserts one stale marker when SSE stops without a new host timestamp',()=>{let h=sampleHistory([],snapshot(),baseTime);h=sampleHistory(h,snapshot(),baseTime+6000);expect(h).toHaveLength(2);expect(h.at(-1)?.down).toBeNull();expect(h.at(-1)?.memory).toBeNull();expect(h.at(-1)?.requests).toBeNull();expect(sampleHistory(h,snapshot(),baseTime+7000)).toHaveLength(2);});
 it('immediately marks all graph readings unavailable after the retry budget is exhausted',()=>{const h=sampleHistory(sampleHistory([],snapshot(),baseTime),snapshot(0,{_feedUnavailable:true}),baseTime+1);expect(h.at(-1)?.down).toBeNull();expect(h.at(-1)?.memory).toBeNull();expect(h.at(-1)?.requests).toBeNull();});
 it('retains at most 300 points from the last five minutes',()=>{let h=sampleHistory([],snapshot(),baseTime);for(let i=1;i<400;i++)h=sampleHistory(h,snapshot(i*1000),baseTime+i*1000);expect(h.length).toBeLessThanOrEqual(300);expect(h[0].time).toBeGreaterThanOrEqual(baseTime+99000);});
});
describe('device authoritative confirmation deadline',()=>{
 const c={_receivedAt:baseTime,device:{pending:true,session:42,current_time_ms:10000,confirm_deadline_ms:40000}};
 it('counts down from response receipt without resetting on new host events',()=>{expect(countdown(c,snapshot(),baseTime)).toBe(30);expect(countdown(c,snapshot(1000),baseTime+1000)).toBe(29);expect(countdown(c,snapshot(20000),baseTime+20000)).toBe(10);});
 it('does not use old firmware sampled time to guess remaining seconds',()=>{expect(countdown({_receivedAt:baseTime,device:{pending:true,session:42,confirm_deadline_ms:40000}},snapshot(),baseTime)).toBeNull();});
 it('does not confirm across sessions or after telemetry becomes stale',()=>{expect(countdown({...c,device:{...c.device,session:9}},snapshot(),baseTime)).toBeNull();expect(countdown(c,snapshot(),baseTime+6000)).toBeNull();expect(countdown(c,snapshot(31000),baseTime+31000)).toBe(0);});
});
describe('rendered product boundaries',()=>{
 const ui:UIContext={state:snapshot(),config:{host:{serial_port:'COM4',baud:115200,flow_control:false},device:{effective:{}}},capabilities:{},deviceConfig:{},isFresh:true,kind:'USB',blocked:false,pending:false,active:0,baseURL:'http://localhost:8765/v1',statusGood:true,run:vi.fn(),reload:vi.fn(),readConfig:vi.fn(),saveHost:vi.fn(),saveDevice:vi.fn(),action:vi.fn(),setError:vi.fn(),onStop:vi.fn()};
 it('shows true native USB state and no baud or flow editing control',()=>{const html=renderToStaticMarkup(<DevicePage ui={ui}/>);expect(html).toContain('原生 USB Serial/JTAG');expect(html).not.toContain('type="number"');expect(html).not.toContain('RTS/CTS 已接线');expect(html).not.toContain('协商并应用');});
 it('renders UART negotiation only for UART devices',()=>{const html=renderToStaticMarkup(<DevicePage ui={{...ui,kind:'UART'}}/>);expect(html).toContain('协商并应用');expect(html).toContain('连接波特率');});
 it('renders redacted password as keep action rather than a value',()=>{const html=renderToStaticMarkup(<ConfigForm fields={deviceFields.slice(0,2)} baseline={{'wifi.password':true,'wifi.ssid':'Lab'}} onSave={vi.fn()}/>);expect(html).toContain('保持已保存的密码');expect(html).not.toContain('value="true"');expect(html).not.toContain('type="password"');});
 it('does not fabricate zero-filled graphs before data exists',()=>{const html=renderToStaticMarkup(<Chart unit="KiB/s" series={[{label:'上传',color:'blue',values:[null,null]}]}/>);expect(html).toContain('正在收集数据');expect(html).toContain('— KiB/s');});
 it('cuts SVG paths where data is missing',()=>{const html=renderToStaticMarkup(<Chart unit="KiB/s" series={[{label:'上传',color:'blue',values:[1,null,2]}]}/>);expect(html).toMatch(/d="M[^\"]* M/);expect(html).toContain('页面打开后的有效采样');});
});
describe('readable change previews and device states',()=>{
 it('shows only changed fields with user units and option labels',()=>{expect(changeSummary(deviceFields,{'telemetry.interval_ms':1500,'logs.level':4,'wifi.ssid':'same'},{'telemetry.interval_ms':1000,'logs.level':3,'wifi.ssid':'same'})).toEqual([{key:'telemetry.interval_ms',label:'设备状态采样间隔',before:'1 秒',after:'1.5 秒'},{key:'logs.level',label:'设备日志详细程度',before:'信息（推荐）',after:'调试'}]);});
 it('never puts either old or edited passwords into preview text or rendered HTML',()=>{const changes=changeSummary(deviceFields,{'wifi.password':'new-secret-marker'},{'wifi.password':'old-secret-marker'},'replace');const serialized=JSON.stringify(changes),html=renderToStaticMarkup(<ChangeSummary changes={changes}/>);expect(serialized+html).not.toContain('secret-marker');expect(html).toContain('已设置密码');expect(html).toContain('替换为新密码');expect(html).toContain('尚未写入配置');});
 it('distinguishes keeping a secret from deliberately using an open network',()=>{expect(changeSummary(deviceFields,{}, {'wifi.password':true},'keep')).toEqual([]);expect(changeSummary(deviceFields,{}, {'wifi.password':true},'open')[0].after).toBe('开放网络（无需密码）');});
 it('does not hide an invalid edit from the pre-save summary',()=>{expect(changeSummary(hostFields,{'max_concurrent':5},{'max_concurrent':4})[0].after).toBe('5 路');});
 it('uses installed IDF meanings and preserves unknown enum values',()=>{expect(resetReason(3)).toBe('软件重启');expect(imageState(2)).toBe('已确认有效');expect(imageState(99)).toBe('未知（99）');expect(resetReason(null)).toBe('未读取');expect(resetReason(90)).toBe('未知（90）');});
 it('labels weak RSSI without presenting missing values as good signal',()=>{expect(signalQuality(-78)).toBe('较弱');expect(signalQuality(-75)).toBe('一般');expect(signalQuality(-67)).toBe('良好');expect(signalQuality(null)).toBe('未采集');});
});
