import React,{useEffect,useState} from 'react';
import {request} from './api';
import {Obj,bytes,deviceFields,fmt,hostFields,number,object,imageState,resetReason,signalQuality} from './model';
import {Card,ConfigForm,Details,Icon,hasUnsavedChanges,useUnsavedChanges} from './components';
export type UIContext={state:Obj;config:Obj;capabilities:Obj;deviceConfig:Obj;isFresh:boolean;kind:string;blocked:boolean;pending:boolean;active:number;baseURL:string;statusGood:boolean;run:(action:()=>Promise<unknown>,success?:string)=>Promise<boolean>;reload:()=>Promise<void>;readConfig:()=>Promise<Obj>;saveHost:(patch:Obj)=>Promise<boolean>;saveDevice:(patch:Obj)=>Promise<boolean>;action:(path:string,body?:unknown,success?:string)=>void;setError:(s:string)=>void;onStop:()=>void};
const field=(keys:string[],device=false)=>(device?deviceFields:hostFields).filter(f=>keys.includes(f.key));
async function copy(value:string){if(!navigator.clipboard)throw new Error('浏览器不支持自动复制，请选择文本后复制。');await navigator.clipboard.writeText(value);}
export function AppsPage({ui:u}:{ui:UIContext}){
 const [token,setToken]=useState(''),[models,setModels]=useState<Obj[]>([]),[checked,setChecked]=useState(false);
 useEffect(()=>{if(!token)return;const timer=setTimeout(()=>setToken(''),30000);return()=>clearTimeout(timer);},[token]);
 return <><div className="split"><Card title="连接你的 AI 应用" description="选择 OpenAI Compatible / OpenAI 兼容服务"><ol className="steps"><li><b>1</b><div><strong>填写本地地址</strong><p>Base URL 包含 /v1。管理页面端口不用于模型调用。</p><div className="copy-box"><code>{u.baseURL||'正在读取实际监听地址…'}</code><button disabled={!u.baseURL||u.blocked} aria-label="复制 Base URL" onClick={()=>void u.run(()=>copy(u.baseURL),'本地 API 地址已复制。')}><Icon name="copy"/></button></div></div></li><li><b>2</b><div><strong>粘贴本地 API Key</strong><p>这是本地代理的访问凭据，上游密钥由后台自动使用。</p><div className="actions"><button className="primary" disabled={u.blocked} onClick={()=>void u.run(async()=>{const v=object(await request('/api-token'));await copy(v.token);},'本地 API Key 已复制。')}>复制本地 API Key</button><button disabled={u.blocked} onClick={()=>void u.run(async()=>{const v=object(await request('/api-token'));setToken(v.token);},'令牌显示 30 秒后自动隐藏。')}>临时显示</button></div>{token&&<div className="secret-box"><input aria-label="本地 API Key" readOnly value={token} onFocus={e=>e.currentTarget.select()}/><button onClick={()=>setToken('')}>隐藏</button></div>}</div></li><li><b>3</b><div><strong>获取模型并开始对话</strong><p>在应用中点击“获取模型”，或用下方检查确认服务商的真实模型列表。</p></div></li></ol></Card><Card title="接入提示"><div className="guide-tile"><Icon name="plug"/><h3>Cherry Studio / IDE</h3><p>供应商选 OpenAI 兼容，填写左侧地址与本地 API Key，再选择上游提供的模型。</p></div><dl className="detail-list"><div><dt>API 地址</dt><dd>{u.baseURL||'未读取'}</dd></div><div><dt>管理页面</dt><dd>当前页面，无需登录</dd></div><div><dt>模型 API 认证</dt><dd>仍需本地 API Key</dd></div></dl><p className="hint">401：检查 Key；503：检查设备、Wi-Fi、暂停状态及并发。粘贴 Key 时请勿加入空格、引号或转义符。</p><p className="hint">当前支持聊天补全、模型、文件和微调任务家族。具体服务商可能只提供其中部分能力。</p></Card></div><Card title="当前可用模型" description="通过本机代理与 ESP32 查询，不使用电脑的直接网络出口" action={<button className="primary" disabled={u.blocked||!u.statusGood} onClick={()=>void u.run(async()=>{const v=object(await request('/models'));if(!Array.isArray(v.data))throw new Error('服务商没有返回可识别的模型列表。');setModels(v.data);setChecked(true);},'已通过 ESP32 获取当前上游模型列表。')}>检查连接并获取模型</button>}>{checked?<div className="model-grid">{models.length?models.map((m,i)=><div className="model-item" key={m.id||i}><span className="status-dot good"/><div><strong>{String(m.id||'未命名')}</strong><small>{String(m.owned_by||'上游提供')}</small></div><button aria-label={`复制模型 ${m.id}`} onClick={()=>void u.run(()=>copy(String(m.id)),'模型名称已复制。')}><Icon name="copy"/></button></div>):<p className="hint">上游返回了空模型列表。</p>}</div>:<div className="empty-state compact"><Icon name="grid"/><p>尚未查询模型，点击检查即可获取。</p></div>}</Card></>;
}
export function DevicePage({ui:u}:{ui:UIContext}){
 const [port,setPort]=useState(u.config.host?.serial_port||''),[ports,setPorts]=useState<Obj[]>([]),[baud,setBaud]=useState(u.config.host?.baud||115200),[flow,setFlow]=useState(Boolean(u.config.host?.flow_control)),[manualUART,setManualUART]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[scan,setScan]=useState<Obj[]>([]),[scanned,setScanned]=useState(false),[selectedSSID,setSelectedSSID]=useState('');
 useUnsavedChanges(Boolean(password));
 useEffect(()=>{if(!port&&u.config.host?.serial_port)setPort(u.config.host.serial_port);setBaud(u.config.host?.baud||115200);setFlow(Boolean(u.config.host?.flow_control));},[u.config.host?.serial_port,u.config.host?.baud,u.config.host?.flow_control]);
 const ready=u.isFresh&&Boolean(u.config.device),link=u.state.connection||u.state.link||{},net=u.state.device?.network||{},usb=u.kind==='USB',uart=u.kind==='UART';
 useEffect(()=>{let alive=true;void request('/ports').then(p=>{if(alive)setPorts(Array.isArray(p)?p:[]);}).catch(()=>{});return()=>{alive=false;};},[]);
 return <><div className="split"><Card title="设备连接" description="后台独占设备端口，关闭页面不影响连接"><div className="device-identity"><span className="device-glyph"><Icon name="device"/></span><div><strong>ESP32-S3</strong><p>{u.kind==='未知'?'连接后识别传输方式':usb?'原生 USB Serial/JTAG':'UART 串口'} · {link.port||'尚未连接'}</p></div><span className="pill">{u.state.connected?'已连接':'未连接'}</span></div><label className="field">设备端口<input list="ports" placeholder="例如 COM4" value={port} onChange={e=>setPort(e.target.value)}/><datalist id="ports">{ports.map(p=><option key={p.name} value={p.name}>{p.description}</option>)}</datalist><small>可从检测列表选择，也可手动填写。</small></label>{u.kind==='未知'&&<label className="switch-line"><input type="checkbox" checked={manualUART} onChange={e=>setManualUART(e.target.checked)}/>我正在使用外接 UART 转换器</label>}{(uart||u.kind==='未知'&&manualUART)&&<div className="form-grid"><label className="field">连接波特率<input type="number" min="9600" max="3000000" value={baud} onChange={e=>setBaud(Number(e.target.value))}/><small>设备重启恢复为 115200；已连接时请使用下方协商表单。</small></label><label className="switch-line"><input type="checkbox" checked={flow} onChange={e=>setFlow(e.target.checked)}/>RTS/CTS 已接线</label></div>}{usb&&<div className="info-box">当前使用原生 USB。UART 波特率和 RTS/CTS 不参与此连接，提速不需要修改波特率。</div>}<div className="actions"><button className="primary" disabled={u.blocked||!port.trim()} onClick={()=>{if(u.active>0&&!window.confirm(`连接设备会中断 ${u.active} 个活动请求，继续吗？`))return;u.action('/connect',{port:port.trim(),baud:usb||!manualUART&&!uart?115200:baud,flow_control:usb?false:flow},'设备连接已更新。');}}>连接设备</button><button disabled={u.blocked} onClick={()=>void u.run(async()=>{const p=await request('/ports');setPorts(Array.isArray(p)?p:[]);},'已重新检测设备端口。')}>检测端口</button><button disabled={u.blocked||!u.state.connected} onClick={()=>{if(u.active>0&&!window.confirm(`断开会中断 ${u.active} 个请求，继续吗？`))return;u.action('/disconnect',undefined,'已断开设备并停止自动重连。');}}>断开</button></div></Card>
 <Card title={u.state.paired?'设备已安全配对':'完成设备配对'} description="使用首次烧录生成的设备配对凭据，与网页登录无关">{u.state.paired&&<div className="paired-state"><Icon name="check"/><strong>凭据已验证</strong><p>后台会自动使用已保存的凭据重新连接设备。</p></div>}<details open={!u.state.paired}><summary>{u.state.paired?'重新配对设备':'填写配对凭据'}</summary><form onSubmit={e=>{e.preventDefault();void u.run(async()=>{await request('/pair','POST',{username,password});setPassword('');await u.reload();},'设备已配对。');}}><div className="form-grid"><label className="field">配对用户名<input autoComplete="off" value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="field">配对密码<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label></div><button className="primary" disabled={u.blocked||!u.state.connected||!username||!password}>验证并配对</button></form></details></Card></div>
 <Card title="Wi-Fi 网络" description="网络变更会暂时中断设备访问上游，请在无活动请求时修改" action={<button disabled={u.blocked||!ready||u.pending||u.active>0} onClick={()=>void u.run(async()=>{const v=object(await request('/diagnostics','POST',{action:'wifi_scan'}));setScan(Array.isArray(v.networks)?v.networks:[]);setScanned(true);},'扫描完成，点击网络名称即可填入表单。')}>扫描附近网络</button>}>{scanned&&<div className="scan-list">{scan.length?scan.map((n,i)=><button key={i} type="button" disabled={!n.ssid||u.blocked||u.pending} onClick={()=>setSelectedSSID(String(n.ssid))}><strong>{n.ssid||'隐藏网络'}</strong><span>{fmt(n.rssi_dbm)} dBm · {n.authmode===0?'开放网络':'需密码'}</span><span>选择</span></button>):<p>本次没有扫描到网络，仍可手工输入。</p>}</div>}<ConfigForm fields={field(['wifi.ssid','wifi.password'],true)} preset={selectedSSID?{'wifi.ssid':selectedSSID}:undefined} baseline={u.deviceConfig} onSave={u.saveDevice} disabled={u.blocked||!ready||u.pending} device label="应用 Wi-Fi 设置"/>{!ready&&<p className="hint">连接并配对设备后，即可读取和修改网络设置。</p>}<details className="advanced"><summary>高级网络设置 <span>主机名与手动 IPv4</span></summary><ConfigForm fields={field(['wifi.hostname','ip.dhcp','ip.address','ip.gateway','ip.netmask','ip.dns'],true)} baseline={u.deviceConfig} onSave={u.saveDevice} disabled={u.blocked||!ready||u.pending} device/></details></Card>
 {uart&&<Card title="UART 传输参数" description="双端协商切换；失败时自动返回恢复参数"><ConfigForm fields={field(['uart.baud','uart.flow_control'],true)} hidden={!(u.capabilities.device?.build?.['uart.rts']>=0&&u.capabilities.device?.build?.['uart.cts']>=0)?['uart.flow_control']:[]} baseline={u.deviceConfig} onSave={u.saveDevice} disabled={u.blocked||!ready||u.pending} device label="协商并应用"/></Card>}
 <Card title="当前网络信息"><dl className="inline-details"><div><dt>网络</dt><dd>{u.isFresh?net.ssid||'未连接':'—'}</dd></div><div><dt>设备 IP</dt><dd>{u.isFresh?net.address||'未获取':'—'}</dd></div><div><dt>信号</dt><dd>{u.isFresh&&net.connected?`${signalQuality(net.rssi_dbm)} · ${fmt(net.rssi_dbm)} dBm`:'—'}</dd></div><div><dt>Wi-Fi 重连</dt><dd>{u.isFresh?fmt(net.reconnects):'—'}</dd></div></dl></Card></>;
}
export function SettingsPage({ui:u}:{ui:UIContext}){
 const [section,setSection]=useState('service'),[key,setKey]=useState('');useUnsavedChanges(Boolean(key));
 return <><div className="tabs" role="tablist" aria-label="设置分类">{[['service','模型服务'],['requests','请求与超时'],['advanced','高级设置']].map(([id,l])=><button role="tab" aria-selected={section===id} key={id} className={section===id?'active':''} onClick={()=>{if(id===section||!hasUnsavedChanges()||window.confirm('此处有未保存的修改，切换设置分类会丢失输入。继续吗？'))setSection(id);}}>{l}</button>)}</div>{section==='service'&&<div className="split"><Card title="上游模型服务" description="ESP32 负责联网，电脑代理处理 HTTP 与 TLS"><ConfigForm fields={field(['upstream_url'])} baseline={object(u.config.host)} onSave={u.saveHost} disabled={u.blocked||!u.config.host}/><div className="info-box">客户端填写本地地址 {u.baseURL||'localhost:8765/v1'}，此处填写服务商的地址。</div></Card><Card title="上游凭据" description={u.config.secrets?.upstream_key_set?'已安全保存 · 不回读已存密钥':'尚未保存上游密钥'}><form onSubmit={e=>{e.preventDefault();void u.run(async()=>{await request('/credentials','POST',{upstream_key:key});setKey('');await u.readConfig();},'上游密钥已安全保存。');}}><label className="field">替换上游 API Key<input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)}/><small>仅更换密钥时填写。地址与密钥分别保存，不会自动回滚另一项。</small></label><div className="form-footer"><span>机密保存在 Windows 凭据存储</span><button className="primary" disabled={u.blocked||!key.trim()}>保存密钥</button></div></form></Card></div>}
 {section==='requests'&&<Card title="请求控制" description="为后续请求生效；已有请求继续使用原参数"><ConfigForm fields={field(['max_concurrent','connect_timeout_seconds','header_timeout_seconds','idle_timeout_seconds'])} baseline={object(u.config.host)} onSave={u.saveHost} disabled={u.blocked||!u.config.host}/></Card>}
 {section==='advanced'&&<><Card title="本机监听地址" description="仅允许本机回环地址。保存后需要停止并重新启动后台。"><ConfigForm fields={field(['api_listen','admin_listen'])} baseline={object(u.config.host)} onSave={u.saveHost} disabled={u.blocked||!u.config.host}/>{u.config.restart_required&&<div className="notice warning">新地址已保存，等待后台重新启动。当前 API：{u.config.effective_listeners?.api_listen}；管理：{u.config.effective_listeners?.admin_listen}。关闭网页不会重启后台。</div>}</Card><Card title="设备调优" description="通常保持默认即可；这些设置也需要应用后确认保存"><ConfigForm fields={field(['tcp.connect_timeout_ms','tcp.idle_timeout_ms','telemetry.interval_ms','logs.level'],true)} baseline={u.deviceConfig} onSave={u.saveDevice} disabled={u.blocked||!u.isFresh||!u.config.device||u.pending} device/></Card></>}</>;
}
export function MaintenancePage({ui:u}:{ui:UIContext}){
 const [logs,setLogs]=useState<Obj>({}),[diagnostic,setDiagnostic]=useState<unknown>(),[schema,setSchema]=useState<unknown>(),[stateSchema,setStateSchema]=useState<unknown>(),[tasks,setTasks]=useState<unknown>(),[file,setFile]=useState<File>();
 const d=u.state.device||{},ready=u.isFresh&&Boolean(u.config.device);
 const loadLogs=async()=>{const previous=logs._session===d.session&&Array.isArray(logs.device)?logs.device:[];const after=Math.max(0,...previous.map((l:Obj)=>Number(l.id)||0));const v=object(await request('/logs?after='+after));const entries=Array.isArray(v.device)?v.device:[];const merged=new Map([...previous,...entries].map((l:Obj)=>[l.id,l]));setLogs({...v,device:[...merged.values()].slice(-128),_session:d.session});};
 const download=(v:unknown,name:string)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const diagnosticAction=(a:string)=>void u.run(async()=>{const v=await request('/diagnostics','POST',{action:a});if(a==='export'||a==='crash_export')download(v,`uart2llm-${a}.json`);else setDiagnostic(v);},a==='export'||a==='crash_export'?'诊断文件已准备下载。':'诊断已完成。');
 return <><div className="split"><Card title="诊断工具" description="不采集对话正文或上游密钥"><div className="tool-grid"><button disabled={u.blocked||!ready} onClick={()=>diagnosticAction('network')}><Icon name="pulse"/><strong>检查网络</strong><small>读取设备网络状态</small></button><button disabled={u.blocked} onClick={()=>diagnosticAction('export')}><Icon name="copy"/><strong>导出诊断</strong><small>保存配置与状态摘要</small></button><button disabled={u.blocked||!ready||!d.crash?.available} onClick={()=>diagnosticAction('crash_export')}><Icon name="device"/><strong>导出崩溃记录</strong><small>{d.crash?.available?'有可用记录':'暂无崩溃记录'}</small></button></div><div className="actions"><button disabled={u.blocked||!ready||u.pending} onClick={()=>{if(window.confirm(`重新连接 Wi-Fi 会中断当前 ${u.active} 个模型请求，并关闭上游连接；保存的网络配置保持不变。继续吗？`))u.action('/diagnostics',{action:'wifi_reconnect'},'已请求重新连接 Wi-Fi，请等待网络恢复。');}}>重新连接 Wi-Fi</button></div>{diagnostic!==undefined&&<details className="advanced" open><summary>本次网络诊断结果</summary><KeyValues value={{'Wi-Fi 状态':object(diagnostic).network?.connected?'已连接':'未连接','网络名称':object(diagnostic).network?.ssid||'—','设备 IP':object(diagnostic).network?.address||'—','网关':object(diagnostic).network?.gateway||'—','DNS':object(diagnostic).network?.dns||'—','信号':object(diagnostic).network?.connected?String(object(diagnostic).network?.rssi_dbm??'—')+' dBm':'—','重连次数':object(diagnostic).network?.reconnects??'—','内部剩余内存':bytes(object(diagnostic).memory?.internal_free)}}/></details>}</Card><Card title="设备信息" description="硬件配置由固件构建决定"><dl className="detail-list"><div><dt>传输方式</dt><dd>{u.kind==='USB'?'原生 USB Serial/JTAG':u.kind}</dd></div><div><dt>当前固件版本</dt><dd>{u.capabilities.device?.firmware||'未读取'}</dd></div><div><dt>运行时间</dt><dd>{u.isFresh?`${fmt(d.uptime_ms/3600000,1)} 小时`:'—'}</dd></div><div><dt>芯片温度</dt><dd>{u.isFresh&&number(d.temperature_celsius)!==null?`${fmt(d.temperature_celsius,1)} °C`:'暂未采集'}</dd></div><div><dt>Flash / PSRAM</dt><dd>{bytes(u.capabilities.device?.flash_bytes)} / {bytes(u.capabilities.device?.psram_bytes)}</dd></div><div><dt>最近重启原因</dt><dd>{u.isFresh?resetReason(d.reset_reason):'—'}</dd></div></dl></Card></div>
 <Card title="运行日志" description="按需分页读取；再次点击继续读取新记录" action={<button disabled={u.blocked} onClick={()=>void u.run(loadLogs,'运行日志已更新。')}>读取日志</button>}><LogTable logs={logs}/></Card>
 <Card title="更新设备固件" description="选择适用于当前开发板的应用镜像，更新期间保持供电和连接"><div className="firmware-row"><label className="file-picker"><Icon name="device"/><span>{file?file.name:'选择 .bin 应用镜像'}<small>{file?bytes(file.size):'不会把完整文件读入浏览器内存'}</small></span><input aria-label="选择固件文件" type="file" accept=".bin,application/octet-stream" onChange={e=>setFile(e.target.files?.[0])}/></label><button className="primary" disabled={u.blocked||!ready||u.pending||u.active>0||!file} onClick={()=>{if(!file)return;const limit=Math.min(u.capabilities.host?.ota_max_bytes||4194304,u.capabilities.device?.ota_max_bytes||4194304);if(!file.size||file.size>limit){u.setError(`固件大小应为 1 字节至 ${bytes(limit)}。`);return;}if(window.confirm(`将上传 ${file.name} 并重启设备。确认镜像适配开发板并持续供电后继续。`))void u.run(async()=>{await request('/firmware','POST',file);await u.reload();setFile(undefined);},'固件上传已结束，等待设备重新连接并确认启动状态。');}}>上传并更新</button></div>{(u.state.host?.firmware_upload||d.ota?.active)&&<div className="progress-section"><progress max={d.ota?.size||1} value={d.ota?.size?d.ota.offset:undefined}/><p>{d.ota?.size?`${fmt(d.ota.offset/d.ota.size*100)}% · ${bytes(d.ota.offset)} / ${bytes(d.ota.size)}`:'正在上传 / 验证，请保持连接…'}</p></div>}<p className="hint">运行分区：{d.ota?.running_partition||'未读取'} · 镜像状态：{imageState(d.ota?.image_state)}。上传完成与设备启动确认是不同阶段。</p></Card>
 <details className="card advanced"><summary>完整配置与遥测目录 <span>技术支持与高级诊断</span></summary><p className="hint">只读目录；常用参数请在对应页面修改。GPIO 和不支持的能力不会显示为可编辑控件。</p><div className="actions"><button disabled={u.blocked} onClick={()=>void u.run(async()=>{setSchema(await request('/config/schema'));setStateSchema(await request('/state/schema'));},'字段目录已更新。')}>读取完整目录</button><button disabled={u.blocked||!ready} onClick={()=>void u.run(async()=>setTasks(await request('/tasks')),'任务状态已更新。')}>读取任务状态</button></div><details><summary>当前配置（机密仅显示是否设置）</summary><Details value={u.config}/></details><details><summary>字段定义</summary><Details value={schema}/></details><details><summary>遥测定义</summary><Details value={stateSchema}/></details><details><summary>完整实时快照</summary><Details value={u.state}/></details><details><summary>硬件能力与 GPIO</summary><Details value={u.capabilities}/></details><details><summary>任务与栈状态</summary><Details value={tasks}/></details></details>
 <details className="card advanced danger-zone"><summary>设备与后台维护 <span>重启、恢复默认和停止服务</span></summary><p>这些操作可能中断当前请求。关闭网页不会停止代理。</p><div className="actions"><button disabled={u.blocked||!ready} onClick={()=>window.confirm(`重启设备会中断当前 ${u.active} 个请求，继续吗？`)&&u.action('/device/action',{action:'reboot'},'已请求重启设备，等待自动重连。')}>重启设备</button><button disabled={u.blocked||!ready||!d.crash?.available} onClick={()=>window.confirm('清除已保存的崩溃数据？需要保留时请先导出。')&&u.action('/device/action',{action:'clear_crash'},'崩溃记录已清除。')}>清除崩溃记录</button><button className="danger" disabled={u.blocked||!ready||u.active>0} onClick={()=>window.confirm('恢复设备默认设置会清除 Wi-Fi 等设备配置并断开连接，保留配对身份。确定继续？')&&u.action('/device/action',{action:'factory_reset'},'设备恢复默认操作已提交。')}>恢复设备默认设置</button><button className="danger" disabled={u.blocked} onClick={()=>{if(window.confirm('停止后台将中断所有请求，并使管理页面暂时无法访问。继续吗？'))void u.run(async()=>{await request('/shutdown','POST');u.onStop();},'后台正在停止。重新启动后才能使用。');}}>停止代理后台</button></div></details></>;
}
function KeyValues({value}:{value:Obj}) {return <dl className="detail-list">{Object.entries(value).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl>;}
function LogTable({logs}:{logs:Obj}) {const entries:Obj[]=[...(Array.isArray(logs.host)?logs.host.map((l:Obj)=>({...l,source:'电脑'})):[]),...(Array.isArray(logs.device)?logs.device.map((l:Obj)=>({...l,source:'设备'})):[])];return entries.length?<div className="table-scroll"><table><thead><tr><th>来源 / 时间</th><th>级别 / 事件</th><th>说明</th></tr></thead><tbody>{entries.slice(-80).reverse().map((l,i)=><tr key={i}><td>{l.source}<small>{l.time?new Date(l.time).toLocaleTimeString('zh-CN'):l.time_ms!==undefined?`开机后 ${fmt(l.time_ms/1000)} 秒`:'—'}</small></td><td>{l.level||l.event||'状态'}</td><td>{l.message||l.detail||'—'}</td></tr>)}</tbody></table></div>:<p className="empty-copy">点击“读取日志”查看后台和设备保留的记录。</p>;}

